
import { AppStrings, LanguageCode } from './types';

export const LANGUAGES: { code: LanguageCode; name: string; dir: 'rtl' | 'ltr' }[] = [
  { code: 'ar', name: 'العربية', dir: 'rtl' },
  { code: 'en', name: 'English', dir: 'ltr' },
  { code: 'de', name: 'Deutsch', dir: 'ltr' },
  { code: 'uk', name: 'Українська', dir: 'ltr' },
  { code: 'es', name: 'Español', dir: 'ltr' },
  { code: 'tr', name: 'Türkçe', dir: 'ltr' },
  { code: 'ru', name: 'Русский', dir: 'ltr' },
  { code: 'hu', name: 'Magyar', dir: 'ltr' },
  { code: 'fa', name: 'فارسی', dir: 'rtl' },
  { code: 'sr', name: 'Српски', dir: 'ltr' },
  { code: 'fr', name: 'Français', dir: 'ltr' },
  { code: 'it', name: 'Italiano', dir: 'ltr' },
  { code: 'ja', name: '日本語', dir: 'ltr' },
  { code: 'zh-CN', name: '简体中文', dir: 'ltr' },
  { code: 'ur', name: 'اردو', dir: 'rtl' },
  { code: 'ro', name: 'Română', dir: 'ltr' },
  { code: 'hi', name: 'हिन्दी', dir: 'ltr' },
];

const EN_STRINGS: AppStrings = {
  appName: "Deutsch mit Yaser",
  tagline: "Your companion for German grammar",
  verbs: "Verbs",
  verbsDesc: "Conjugation, tenses, and examples",
  nouns: "Nouns",
  nounsDesc: "Article (der, die, das) and pronunciation",
  grammar: "Grammar",
  grammarDesc: "Comprehensive lessons (A1-C2)",
  tools: "Tools",
  toolsDesc: "Prepositions, Conjunctions, Adverbs",
  settings: "Settings",
  back: "Back",
  enterNoun: "Enter a German noun (no article)",
  checkNoun: "Check",
  enterVerb: "Enter a German verb (Infinitive)",
  continue: "Continue",
  tenses: "Tenses",
  forms: "Forms",
  passive: "Passive Voice",
  loading: "Loading...",
  apiKeyLabel: "API Key (Gemini)",
  apiKeyPlaceholder: "Enter your API Key here",
  save: "Save",
  missingKey: "Please enter API Key in Settings",
  examples: "Examples",
  pronunciation: "Pronounce",
  askAi: "Ask Teacher",
  testMe: "Quiz Me",
  chatTitle: "AI Tutor",
  chatPlaceholder: "Ask about this example...",
  send: "Send",
  nounResult: "Result",
  article: "Article",
  word: "Word",
  translation: "Translation",
  showMeanings: "Meanings & Usage",
  meaningsTitle: "Meanings & Usage",
  nounCasesTitle: "Noun Cases",
  selectLevel: "Select Level",
  topicsFor: "Topics for",
  toolsCategories: "Tool Categories",
  selectTool: "Select Tool",
  language: "Language",
  selectLanguage: "Select App Language",
  smartStorage: "Renewable Smart Examples",
  smartStorageDesc: "⚠️ Bypasses cache to fetch fresh data. Increases API usage.",
  audioSettings: "Audio Settings",
  audioPreload: "Preload",
  audioOnDemand: "On Demand",
  audioDisabled: "Disable Audio",
  srsSystem: "Spaced Repetition System",
  srsDesc: "Smart review for difficult words",
  copyright: "Copyright © 2026 Yaser Hasan",
  disclaimer: "Disclaimer: Educational results generated by AI",
  privacy: "Privacy: Data stored locally only",
  needKeyTitle: "Need a key?",
  getKeyLink: "Get a free Google Gemini API Key",
  howToGetKeyLink: "How to Get Your Google API Key",
  convTitle: "Conversations",
  convDesc: "Interactive dialogues by level",
  convTopicLabel: "What do you want to talk about?",
  convTopicPlaceholder: "e.g. At the train station, Booking a hotel...",
  convLengthLabel: "Length",
  convShort: "Short",
  convMedium: "Medium",
  convLong: "Long",
  convStart: "Start Conversation",
  convShowTrans: "Show Translation",
  convHideTrans: "Hide Translation",
  convSlowSpeed: "Slow Speed",
  convNormalSpeed: "Normal Speed",
  convExtractKeywords: "Extract Keywords",
  convKeywordsTitle: "Key Vocabulary",
  convAddMoreLabel: "Extend Conversation",
  convAddMorePlaceholder: "What if I said... (AI will respond)",
  convAddButton: "Add",
  convSuggestedTopics: "Suggested Topics",
  convHistory: "Previous Conversations",
  convNoHistory: "No saved conversations yet",
  convAustrianLabel: "Viennese & Austrian Dialect",
  convAustrianDisclaimer: "Note: Audio pronunciation may not perfectly match the dialect. Use the text for learning.",
  nounPlural: "Plural",
  nounHistory: "Search History",
  convTopicsList: ["At the Restaurant", "Job Interview", "At the Doctor", "Shopping", "Meeting People", "At the Airport"],
  categories: {
    tenses: {
      prasens: "Present (Präsens)",
      prateritum: "Simple Past (Präteritum)",
      perfekt: "Perfect (Perfekt)",
      plusquamperfekt: "Pluperfect (Plusquamperfekt)",
      futur1: "Future I",
      futur2: "Future II"
    },
    forms: {
      konjunktiv1: "Subjunctive I",
      konjunktiv2: "Subjunctive II",
      imperativ: "Imperative"
    },
    passive: {
      past: "Past",
      present: "Present",
      perfect: "Perfect",
      future: "Future"
    }
  },
  toolCategories: {
    prepositions: 'Prepositions',
    conjunctions: 'Conjunctions',
    adverbs: 'Adverbs',
    particles: 'Particles',
    pronouns: 'Pronouns',
    interrogatives: 'Interrogatives'
  }
};

const AR_STRINGS: AppStrings = {
  ...EN_STRINGS,
  appName: "Deutsch mit Yaser",
  tagline: "رفيقك لتعلم قواعد اللغة الألمانية",
  verbs: "الأفعال",
  verbsDesc: "تصريف، أزمنة، وأمثلة",
  nouns: "الأسماء",
  nounsDesc: "الأداة (der, die, das) والنطق",
  grammar: "القواعد",
  grammarDesc: "دروس شاملة لكل المستويات (A1-C2)",
  tools: "الأدوات",
  toolsDesc: "حروف الجر، العطف، والظروف",
  settings: "الإعدادات",
  back: "رجوع",
  enterNoun: "أدخل اسماً بالألمانية (بدون أداة)",
  checkNoun: "تدقيق",
  enterVerb: "أدخل فعلاً بالألمانية (المصدر)",
  continue: "متابعة",
  tenses: "الأزمنة",
  forms: "الصيغ",
  passive: "المبني للمجهول",
  loading: "جاري التحميل...",
  apiKeyLabel: "مفتاح API (Gemini)",
  apiKeyPlaceholder: "أدخل مفتاح API الخاص بك هنا",
  save: "حفظ",
  missingKey: "الرجاء إدخال مفتاح API في الإعدادات",
  examples: "أمثلة",
  pronunciation: "نطق",
  askAi: "اسأل المعلم",
  testMe: "اختبرني",
  chatTitle: "المعلم الذكي",
  chatPlaceholder: "اسأل عن هذا المثال...",
  send: "إرسال",
  nounResult: "النتيجة",
  article: "الأداة",
  word: "الكلمة",
  translation: "الترجمة",
  showMeanings: "المعاني والاستخدامات",
  meaningsTitle: "معاني واستخدامات",
  nounCasesTitle: "استخدامات الاسم",
  selectLevel: "اختر المستوى",
  topicsFor: "مواضيع المستوى",
  toolsCategories: "أقسام الأدوات",
  selectTool: "اختر الأداة",
  language: "اللغة",
  selectLanguage: "اختر لغة التطبيق",
  smartStorage: "أمثلة ذكية متجددة",
  smartStorageDesc: "⚠️ تفعيل هذا الخيار يتجاهل الذاكرة ويجلب بيانات جديدة، مما يزيد من استهلاك رصيد API",
  audioSettings: "إعدادات الصوت",
  audioPreload: "تنزيل مسبق",
  audioOnDemand: "عند الطلب",
  audioDisabled: "تعطيل الصوت",
  srsSystem: "نظام التكرار المتباعد",
  srsDesc: "تذكير ذكي بالكلمات الصعبة",
  copyright: "Copyright © 2026 Yaser Hasan",
  disclaimer: "إخلاء مسؤولية: النتائج تعليمية ومولدة بواسطة AI",
  privacy: "الخصوصية: يتم حفظ بياناتك محلياً فقط",
  needKeyTitle: "هل تحتاج إلى مفتاح؟",
  getKeyLink: "احصل على مفتاح Gemini API مجاناً",
  howToGetKeyLink: "كيفية الحصول على مفتاح Google API",
  convTitle: "توليد المحادثات",
  convDesc: "محادثات تفاعلية حسب المستوى",
  convTopicLabel: "عن ماذا تريد أن تتحدث؟",
  convTopicPlaceholder: "مثال: في محطة القطار، حجز فندق...",
  convLengthLabel: "طول المحادثة",
  convShort: "قصيرة",
  convMedium: "متوسطة",
  convLong: "طويلة",
  convStart: "بدء المحادثة",
  convShowTrans: "إظهار الترجمة",
  convHideTrans: "إخفاء الترجمة",
  convSlowSpeed: "نطق بطيء",
  convNormalSpeed: "نطق عادي",
  convExtractKeywords: "استخراج أهم الكلمات",
  convKeywordsTitle: "كلمات مفتاحية",
  convAddMoreLabel: "توسيع المحادثة",
  convAddMorePlaceholder: "ماذا لو قلت... (سيقوم الـ AI بالرد)",
  convAddButton: "أضف",
  convSuggestedTopics: "مواضيع مقترحة",
  convHistory: "المحادثات السابقة",
  convNoHistory: "لا توجد محادثات محفوظة بعد",
  convAustrianLabel: "لهجة فيينا والنمسا",
  convAustrianDisclaimer: "تنبيه: النطق الصوتي قد لا يطابق اللهجة بدقة، استخدم النص المكتوب للتعلم.",
  nounPlural: "الجمع",
  nounHistory: "سجل البحث",
  convTopicsList: ["في المطعم", "مقابلة عمل", "عند الطبيب", "التسوق", "التعارف", "في المطار"],
  categories: {
    tenses: {
      prasens: "المضارع (Präsens)",
      prateritum: "الماضي البسيط (Präteritum)",
      perfekt: "الماضي التام (Perfekt)",
      plusquamperfekt: "الماضي الأسبق (Plusquamperfekt)",
      futur1: "المستقبل الأول (Futur I)",
      futur2: "المستقبل الثاني (Futur II)"
    },
    forms: {
      konjunktiv1: "تمني 1 (Konjunktiv I)",
      konjunktiv2: "تمني 2 (Konjunktiv II)",
      imperativ: "الأمر (Imperativ)"
    },
    passive: {
      past: "الماضي (Past)",
      present: "المضارع (Present)",
      perfect: "التام (Perfect)",
      future: "المستقبل (Future)"
    }
  },
  toolCategories: {
    prepositions: 'حروف الجر',
    conjunctions: 'أدوات العطف',
    adverbs: 'الظروف',
    particles: 'الجسيمات',
    pronouns: 'الضمائر',
    interrogatives: 'أدوات الاستفهام'
  }
};

const DE_STRINGS: AppStrings = {
  ...EN_STRINGS,
  appName: "Deutsch mit Yaser",
  tagline: "Dein Begleiter für deutsche Grammatik",
  verbs: "Verben",
  verbsDesc: "Konjugation, Zeitformen und Beispiele",
  nouns: "Nomen",
  nounsDesc: "Artikel (der, die, das) und Aussprache",
  grammar: "Grammatik",
  grammarDesc: "Umfassende Lektionen (A1-C2)",
  tools: "Werkzeuge",
  toolsDesc: "Präpositionen, Konjunktionen, Adverbien",
  settings: "Einstellungen",
  back: "Zurück",
  enterNoun: "Gib ein deutsches Nomen ein (ohne Artikel)",
  checkNoun: "Prüfen",
  enterVerb: "Gib ein deutsches Verb ein (Infinitiv)",
  continue: "Weiter",
  tenses: "Zeitformen",
  forms: "Formen",
  passive: "Passiv",
  loading: "Laden...",
  apiKeyLabel: "API-Schlüssel (Gemini)",
  apiKeyPlaceholder: "Gib hier deinen API-Schlüssel ein",
  save: "Speichern",
  missingKey: "Bitte API-Schlüssel in den Einstellungen eingeben",
  examples: "Beispiele",
  pronunciation: "Aussprache",
  askAi: "Frag den Lehrer",
  testMe: "Teste mich",
  chatTitle: "KI-Tutor",
  chatPlaceholder: "Frag nach diesem Beispiel...",
  send: "Senden",
  nounResult: "Ergebnis",
  article: "Artikel",
  word: "Wort",
  translation: "Übersetzung",
  showMeanings: "Bedeutungen & Nutzung",
  meaningsTitle: "Bedeutungen & Nutzung",
  nounCasesTitle: "Kasus",
  selectLevel: "Stufe wählen",
  topicsFor: "Themen für",
  toolsCategories: "Werkzeugkategorien",
  selectTool: "Werkzeug wählen",
  language: "Sprache",
  selectLanguage: "App-Sprache wählen",
  smartStorage: "Intelligente Beispiele",
  smartStorageDesc: "⚠️ Umgeht den Cache für neue Daten. Erhöht API-Nutzung.",
  audioSettings: "Audio-Einstellungen",
  audioPreload: "Vorladen",
  audioOnDemand: "Bei Bedarf",
  audioDisabled: "Audio deaktivieren",
  srsSystem: "Spaced Repetition System",
  srsDesc: "Intelligente Wiederholung für schwierige Wörter",
  copyright: "Copyright © 2026 Yaser Hasan",
  disclaimer: "Haftungsausschluss: Ergebnisse von KI generiert",
  privacy: "Datenschutz: Daten nur lokal gespeichert",
  needKeyTitle: "Brauchst du einen Schlüssel?",
  getKeyLink: "Kostenlosen Gemini API-Schlüssel erhalten",
  howToGetKeyLink: "So erhältst du deinen Google API-Schlüssel",
  convTitle: "Konversationen",
  convDesc: "Interaktive Dialoge nach Niveau",
  convTopicLabel: "Worüber möchtest du sprechen?",
  convTopicPlaceholder: "z.B. Am Bahnhof, Hotelbuchung...",
  convLengthLabel: "Länge",
  convShort: "Kurz",
  convMedium: "Mittel",
  convLong: "Lang",
  convStart: "Start",
  convShowTrans: "Übersetzung anzeigen",
  convHideTrans: "Übersetzung ausblenden",
  convSlowSpeed: "Langsam",
  convNormalSpeed: "Normal",
  convExtractKeywords: "Schlüsselwörter",
  convKeywordsTitle: "Wichtige Vokabeln",
  convAddMoreLabel: "Konversation erweitern",
  convAddMorePlaceholder: "Was wäre wenn ich sage... (KI antwortet)",
  convAddButton: "Hinzufügen",
  convSuggestedTopics: "Vorgeschlagene Themen",
  convHistory: "Verlauf",
  convNoHistory: "Noch keine Konversationen gespeichert",
  convAustrianLabel: "Wiener & Österreichischer Dialekt",
  convAustrianDisclaimer: "Hinweis: Die Audio-Aussprache entspricht möglicherweise nicht exakt dem Dialekt.",
  nounPlural: "Plural",
  nounHistory: "Suchverlauf",
  convTopicsList: ["Im Restaurant", "Vorstellungsgespräch", "Beim Arzt", "Einkaufen", "Leute treffen", "Am Flughafen"],
  categories: {
    tenses: {
      prasens: "Präsens",
      prateritum: "Präteritum",
      perfekt: "Perfekt",
      plusquamperfekt: "Plusquamperfekt",
      futur1: "Futur I",
      futur2: "Futur II"
    },
    forms: {
      konjunktiv1: "Konjunktiv I",
      konjunktiv2: "Konjunktiv II",
      imperativ: "Imperativ"
    },
    passive: {
      past: "Vergangenheit",
      present: "Gegenwart",
      perfect: "Perfekt",
      future: "Zukunft"
    }
  },
  toolCategories: {
    prepositions: 'Präpositionen',
    conjunctions: 'Konjunktionen',
    adverbs: 'Adverbien',
    particles: 'Partikel',
    pronouns: 'Pronomen',
    interrogatives: 'Fragewörter'
  }
};

const ES_STRINGS: AppStrings = {
  ...EN_STRINGS,
  appName: "Deutsch mit Yaser",
  tagline: "Tu compañero de gramática alemana",
  verbs: "Verbos",
  verbsDesc: "Conjugación, tiempos y ejemplos",
  nouns: "Sustantivos",
  nounsDesc: "Artículo (der, die, das) y pronunciación",
  grammar: "Gramática",
  grammarDesc: "Lecciones completas (A1-C2)",
  tools: "Herramientas",
  toolsDesc: "Preposiciones, Conjunciones, Adverbios",
  settings: "Ajustes",
  back: "Atrás",
  enterNoun: "Introduce un sustantivo (sin artículo)",
  checkNoun: "Comprobar",
  enterVerb: "Introduce un verbo (Infinitivo)",
  continue: "Continuar",
  tenses: "Tiempos",
  forms: "Formas",
  passive: "Voz Pasiva",
  loading: "Cargando...",
  apiKeyLabel: "Clave API (Gemini)",
  apiKeyPlaceholder: "Introduce tu clave API aquí",
  save: "Guardar",
  missingKey: "Por favor, introduce la clave API en Ajustes",
  examples: "Ejemplos",
  pronunciation: "Pronunciar",
  askAi: "Preguntar al Maestro",
  testMe: "Examíname",
  chatTitle: "Tutor IA",
  send: "Enviar",
  nounResult: "Resultado",
  article: "Artículo",
  word: "Palabra",
  translation: "Traducción",
  showMeanings: "Significados y Uso",
  meaningsTitle: "Significados",
  nounCasesTitle: "Casos del Sustantivo",
  selectLevel: "Selecciona Nivel",
  topicsFor: "Temas para",
  toolsCategories: "Categorías",
  selectTool: "Selecciona Herramienta",
  language: "Idioma",
  selectLanguage: "Selecciona Idioma",
  smartStorage: "Ejemplos Inteligentes",
  smartStorageDesc: "⚠️ Omite caché para datos nuevos. Aumenta uso de API.",
  audioSettings: "Ajustes de Audio",
  audioPreload: "Precargar",
  audioOnDemand: "Bajo Demanda",
  audioDisabled: "Desactivar Audio",
  srsSystem: "Sistema de Repetición Espaciada",
  srsDesc: "Repaso inteligente para palabras difíciles",
  copyright: "Copyright © 2026 Yaser Hasan",
  disclaimer: "Aviso: Resultados generados por IA",
  privacy: "Privacidad: Datos guardados solo localmente",
  needKeyTitle: "¿Necesitas una clave?",
  getKeyLink: "Obtén una clave API de Gemini gratis",
  howToGetKeyLink: "Cómo obtener tu clave API de Google",
  convTitle: "Conversaciones",
  convDesc: "Diálogos interactivos por nivel",
  convTopicLabel: "¿De qué quieres hablar?",
  convTopicPlaceholder: "ej. En la estación, Reservar hotel...",
  convLengthLabel: "Longitud",
  convShort: "Corta",
  convMedium: "Media",
  convLong: "Larga",
  convStart: "Iniciar Conversación",
  convShowTrans: "Mostrar Traducción",
  convHideTrans: "Ocultar Traducción",
  convSlowSpeed: "Velocidad Lenta",
  convNormalSpeed: "Velocidad Normal",
  convExtractKeywords: "Extraer Palabras Clave",
  convKeywordsTitle: "Vocabulario Clave",
  convAddMoreLabel: "Extender Conversación",
  convAddMorePlaceholder: "¿Y si yo dijera... (IA responderá)",
  convAddButton: "Añadir",
  convSuggestedTopics: "Temas Sugeridos",
  convHistory: "Conversaciones Anteriores",
  convNoHistory: "No hay conversaciones guardadas",
  convAustrianLabel: "Dialecto de Viena y Austria",
  convAustrianDisclaimer: "Nota: La pronunciación puede no coincidir exactamente con el dialecto.",
  nounPlural: "Plural",
  nounHistory: "Historial",
  convTopicsList: ["En el Restaurante", "Entrevista de Trabajo", "En el Médico", "Compras", "Conociendo Gente", "En el Aeropuerto"]
};

const FR_STRINGS: AppStrings = {
  ...EN_STRINGS,
  appName: "Deutsch mit Yaser",
  tagline: "Votre compagnon de grammaire allemande",
  verbs: "Verbes",
  verbsDesc: "Conjugaison, temps et exemples",
  nouns: "Noms",
  nounsDesc: "Article (der, die, das) et prononciation",
  grammar: "Grammaire",
  grammarDesc: "Leçons complètes (A1-C2)",
  tools: "Outils",
  toolsDesc: "Prépositions, Conjonctions, Adverbes",
  settings: "Paramètres",
  back: "Retour",
  enterNoun: "Entrez un nom (sans article)",
  checkNoun: "Vérifier",
  enterVerb: "Entrez un verbe (Infinitif)",
  continue: "Continuer",
  tenses: "Temps",
  forms: "Formes",
  passive: "Voix Passive",
  loading: "Chargement...",
  apiKeyLabel: "Clé API (Gemini)",
  apiKeyPlaceholder: "Entrez votre clé API ici",
  save: "Enregistrer",
  missingKey: "Veuillez entrer la clé API dans les paramètres",
  examples: "Exemples",
  pronunciation: "Prononcer",
  askAi: "Demander au Prof",
  testMe: "Testez-moi",
  chatTitle: "Tutor IA",
  send: "Envoyer",
  nounResult: "Résultat",
  article: "Article",
  word: "Mot",
  translation: "Traduction",
  showMeanings: "Sens et Usage",
  meaningsTitle: "Significations",
  nounCasesTitle: "Cas du Nom",
  selectLevel: "Choisir le Niveau",
  topicsFor: "Sujets pour",
  toolsCategories: "Catégories",
  selectTool: "Choisir l'Outil",
  language: "Langue",
  selectLanguage: "Choisir la Langue",
  smartStorage: "Exemples Intelligents",
  smartStorageDesc: "⚠️ Ignore le cache pour de nouvelles données. Augmente l'usage API.",
  audioSettings: "Paramètres Audio",
  audioPreload: "Précharger",
  audioOnDemand: "À la Demande",
  audioDisabled: "Désactiver Audio",
  srsSystem: "Système de Répétition Espacée",
  srsDesc: "Révision intelligente des mots difficiles",
  copyright: "Copyright © 2026 Yaser Hasan",
  disclaimer: "Avis : Résultats générés par IA",
  privacy: "Confidentialité : Données stockées localement",
  needKeyTitle: "Besoin d'une clé ?",
  getKeyLink: "Obtenir une clé API Gemini gratuite",
  howToGetKeyLink: "Comment obtenir votre clé API Google",
  convTitle: "Conversations",
  convDesc: "Dialogues interactifs par niveau",
  convTopicLabel: "De quoi voulez-vous parler ?",
  convTopicPlaceholder: "ex: À la gare, Réserver un hôtel...",
  convLengthLabel: "Longueur",
  convShort: "Court",
  convMedium: "Moyen",
  convLong: "Long",
  convStart: "Commencer",
  convShowTrans: "Afficher Traduction",
  convHideTrans: "Masquer Traduction",
  convSlowSpeed: "Vitesse Lente",
  convNormalSpeed: "Vitesse Normale",
  convExtractKeywords: "Mots-clés",
  convKeywordsTitle: "Vocabulaire Clé",
  convAddMoreLabel: "Étendre la Conversation",
  convAddMorePlaceholder: "Et si je disais... (IA répondra)",
  convAddButton: "Ajouter",
  convSuggestedTopics: "Sujets Suggérés",
  convHistory: "Historique",
  convNoHistory: "Aucune conversation enregistrée",
  convAustrianLabel: "Dialecte Viennois et Autrichien",
  convAustrianDisclaimer: "Note : La prononciation audio peut ne pas correspondre exactement au dialecte.",
  nounPlural: "Pluriel",
  nounHistory: "Historique",
  convTopicsList: ["Au Restaurant", "Entretien d'Embauche", "Chez le Médecin", "Shopping", "Rencontres", "À l'Aéroport"]
};

const TR_STRINGS: AppStrings = {
  ...EN_STRINGS,
  appName: "Deutsch mit Yaser",
  tagline: "Almanca gramer arkadaşınız",
  verbs: "Fiiller",
  verbsDesc: "Çekimler, zamanlar ve örnekler",
  nouns: "İsimler",
  nounsDesc: "Artikel (der, die, das) ve telaffuz",
  grammar: "Gramer",
  grammarDesc: "Kapsamlı dersler (A1-C2)",
  tools: "Araçlar",
  toolsDesc: "Edatlar, Bağlaçlar, Zarflar",
  settings: "Ayarlar",
  back: "Geri",
  enterNoun: "Bir isim girin (artikelsiz)",
  checkNoun: "Kontrol Et",
  enterVerb: "Bir fiil girin (Mast)",
  continue: "Devam",
  tenses: "Zamanlar",
  forms: "Biçimler",
  passive: "Edilgen Çatı",
  loading: "Yükleniyor...",
  apiKeyLabel: "API Anahtarı (Gemini)",
  apiKeyPlaceholder: "API Anahtarınızı buraya girin",
  save: "Kaydet",
  missingKey: "Lütfen Ayarlarda API Anahtarını girin",
  examples: "Örnekler",
  pronunciation: "Telaffuz",
  askAi: "Öğretmene Sor",
  testMe: "Beni Test Et",
  chatTitle: "Yapay Zeka Eğitmen",
  send: "Gönder",
  nounResult: "Sonuç",
  article: "Artikel",
  word: "Kelime",
  translation: "Çeviri",
  showMeanings: "Anlamlar ve Kullanım",
  meaningsTitle: "Anlamlar",
  nounCasesTitle: "İsim Halleri",
  selectLevel: "Seviye Seç",
  topicsFor: "Konular:",
  toolsCategories: "Kategoriler",
  selectTool: "Araç Seç",
  language: "Dil",
  selectLanguage: "Uygulama Dili",
  smartStorage: "Akıllı Depolama",
  smartStorageDesc: "⚠️ Yeni veri için önbelleği atlar. API kullanımını artırır.",
  audioSettings: "Ses Ayarları",
  audioPreload: "Ön Yükleme",
  audioOnDemand: "İsteğe Bağlı",
  audioDisabled: "Sesi Devre Dışı Bırak",
  srsSystem: "Aralıklı Tekrar Sistemi",
  srsDesc: "Zor kelimeler için akıllı tekrar",
  copyright: "Copyright © 2026 Yaser Hasan",
  disclaimer: "Uyarı: Sonuçlar AI tarafından üretilmiştir",
  privacy: "Gizlilik: Veriler sadece yerel olarak saklanır",
  needKeyTitle: "Anahtara mı ihtiyacınız var?",
  getKeyLink: "Ücretsiz Gemini API Anahtarı Alın",
  howToGetKeyLink: "Google API Anahtarınızı Nasıl Alırsınız",
  convTitle: "Konuşmalar",
  convDesc: "Seviyeye göre diyaloglar",
  convTopicLabel: "Ne hakkında konuşmak istersin?",
  convTopicPlaceholder: "örn. İstasyonda, Otel rezervasyonu...",
  convLengthLabel: "Uzunluk",
  convShort: "Kısa",
  convMedium: "Orta",
  convLong: "Uzun",
  convStart: "Başla",
  convShowTrans: "Çeviriyi Göster",
  convHideTrans: "Çeviriyi Gizle",
  convSlowSpeed: "Yavaş Hız",
  convNormalSpeed: "Normal Hız",
  convExtractKeywords: "Anahtar Kelimeleri Çıkar",
  convKeywordsTitle: "Önemli Kelimeler",
  convAddMoreLabel: "Konuşmayı Genişlet",
  convAddMorePlaceholder: "Ya şöyle dersem... (AI cevaplayacak)",
  convAddButton: "Ekle",
  convSuggestedTopics: "Önerilen Konular",
  convHistory: "Geçmiş Konuşmalar",
  convNoHistory: "Henüz kaydedilmiş konuşma yok",
  convAustrianLabel: "Viyana ve Avusturya Lehçesi",
  convAustrianDisclaimer: "Not: Sesli telaffuz lehçeyle tam eşleşmeyebilir.",
  nounPlural: "Çoğul",
  nounHistory: "Geçmiş",
  convTopicsList: ["Restoranda", "İş Görüşmesi", "Doktorda", "Alışveriş", "Tanışma", "Havalimanında"]
};

const RU_STRINGS: AppStrings = {
  ...EN_STRINGS,
  appName: "Deutsch mit Yaser",
  tagline: "Ваш помощник по немецкой грамматике",
  verbs: "Глаголы",
  verbsDesc: "Спряжение, времена и примеры",
  nouns: "Существительные",
  nounsDesc: "Артикль (der, die, das) и произношение",
  grammar: "Грамматика",
  grammarDesc: "Уроки для всех уровней (A1-C2)",
  tools: "Инструменты",
  toolsDesc: "Предлоги, Союзы, Наречия",
  settings: "Настройки",
  back: "Назад",
  enterNoun: "Введите существительное (без артикля)",
  checkNoun: "Проверить",
  enterVerb: "Введите глагол (Инфинитив)",
  continue: "Далее",
  tenses: "Времена",
  forms: "Формы",
  passive: "Пассивный залог",
  loading: "Загрузка...",
  apiKeyLabel: "API Ключ (Gemini)",
  apiKeyPlaceholder: "Введите ваш API ключ здесь",
  save: "Сохранить",
  missingKey: "Пожалуйста, введите API ключ в настройках",
  examples: "Примеры",
  pronunciation: "Произношение",
  askAi: "Спросить учителя",
  testMe: "Протестируй меня",
  chatTitle: "AI Репетитор",
  send: "Отправить",
  nounResult: "Результат",
  article: "Артикль",
  word: "Слово",
  translation: "Перевод",
  showMeanings: "Значения и использование",
  meaningsTitle: "Значения",
  nounCasesTitle: "Падежи",
  selectLevel: "Выберите уровень",
  topicsFor: "Темы для",
  toolsCategories: "Категории",
  selectTool: "Выберите инструмент",
  language: "Язык",
  selectLanguage: "Выберите язык",
  smartStorage: "Умное хранилище",
  smartStorageDesc: "⚠️ Обновляет данные минуя кэш. Увеличивает использование API.",
  audioSettings: "Настройки аудио",
  audioPreload: "Предзагрузка",
  audioOnDemand: "По требованию",
  audioDisabled: "Отключить звук",
  srsSystem: "Интервальное повторение",
  srsDesc: "Умное повторение сложных слов",
  copyright: "Copyright © 2026 Yaser Hasan",
  disclaimer: "Отказ: Результаты генерируются ИИ",
  privacy: "Приватность: Данные хранятся локально",
  needKeyTitle: "Нужен ключ?",
  getKeyLink: "Получить бесплатный Gemini API ключ",
  howToGetKeyLink: "Как получить Google API ключ",
  convTitle: "Диалоги",
  convDesc: "Интерактивные разговоры",
  convTopicLabel: "О чем вы хотите поговорить?",
  convTopicPlaceholder: "напр. На вокзале, Бронирование отеля...",
  convLengthLabel: "Длина",
  convShort: "Короткий",
  convMedium: "Средний",
  convLong: "Длинный",
  convStart: "Начать",
  convShowTrans: "Показать перевод",
  convHideTrans: "Скрыть перевод",
  convSlowSpeed: "Медленно",
  convNormalSpeed: "Нормально",
  convExtractKeywords: "Ключевые слова",
  convKeywordsTitle: "Важная лексика",
  convAddMoreLabel: "Продолжить диалог",
  convAddMorePlaceholder: "А что если я скажу... (ИИ ответит)",
  convAddButton: "Добавить",
  convSuggestedTopics: "Предложенные темы",
  convHistory: "История",
  convNoHistory: "Нет сохраненных диалогов",
  convAustrianLabel: "Венский и австрийский диалект",
  convAustrianDisclaimer: "Примечание: Аудио произношение может не полностью соответствовать диалекту.",
  nounPlural: "Множественное число",
  nounHistory: "История",
  convTopicsList: ["В ресторане", "Собеседование", "У врача", "Покупки", "Знакомство", "В аэропорту"]
};

const BASE_STRINGS: Record<LanguageCode, AppStrings> = {
  ar: AR_STRINGS,
  en: EN_STRINGS,
  de: DE_STRINGS,
  uk: { ...EN_STRINGS, appName: "Deutsch mit Yaser", tagline: "Ваш помічник у вивченні німецької граматики", verbs: "Дієслова", nouns: "Іменники", grammar: "Граматика", tools: "Інструменти", settings: "Налаштування" },
  es: ES_STRINGS,
  tr: TR_STRINGS,
  ru: RU_STRINGS,
  hu: { ...EN_STRINGS, verbs: "Igék", nouns: "Főnevek", grammar: "Nyelvtan", tools: "Eszközök", settings: "Beállítások" },
  fa: { ...EN_STRINGS, appName: "Deutsch mit Yaser", tagline: "همراه شما برای گرامر آلمانی", verbs: "افعال", nouns: "اسم‌ها", grammar: "گرامر", tools: "ابزارها", settings: "تنظیمات" },
  sr: { ...EN_STRINGS, verbs: "Glagoli", nouns: "Imenice", grammar: "Gramatika", tools: "Alati", settings: "Podešavanja" },
  fr: FR_STRINGS,
  it: { ...EN_STRINGS, verbs: "Verbi", nouns: "Nomi", grammar: "Grammatica", tools: "Strumenti", settings: "Impostazioni", apiKeyLabel: "Chiave API", needKeyTitle: "Hai bisogno di una chiave?", getKeyLink: "Ottieni chiave API gratuita" },
  ja: { ...EN_STRINGS, verbs: "動詞", nouns: "名詞", grammar: "文法", tools: "ツール", settings: "設定", apiKeyLabel: "APIキー", needKeyTitle: "キーが必要ですか？", getKeyLink: "無料のAPIキーを取得" },
  "zh-CN": { ...EN_STRINGS, verbs: "动词", nouns: "名词", grammar: "语法", tools: "工具", settings: "设置", apiKeyLabel: "API 密钥", needKeyTitle: "需要密钥？", getKeyLink: "获取免费 API 密钥" },
  ur: { ...EN_STRINGS, verbs: "فعل", nouns: "اسم", grammar: "گرائمر", tools: "اوزار", settings: "ترتیبات" },
  ro: { ...EN_STRINGS, verbs: "Verbe", nouns: "Substantive", grammar: "Gramatică", tools: "Instrumente", settings: "Setări" },
  hi: { ...EN_STRINGS, verbs: "क्रिया", nouns: "संज्ञा", grammar: "व्याकरण", tools: "उपकरण", settings: "सेटिंग्स" },
};

export const getAppStrings = (lang: LanguageCode): AppStrings => {
  const base = BASE_STRINGS[lang] || BASE_STRINGS.en;
  return { ...EN_STRINGS, ...base };
};

export const TOOL_CATEGORIES = [
  { id: 'prepositions', icon: 'MapPin', descKey: 'prepositions' },
  { id: 'conjunctions', icon: 'List', descKey: 'conjunctions' },
  { id: 'adverbs', icon: 'Clock', descKey: 'adverbs' },
  { id: 'particles', icon: 'Particle', descKey: 'particles' },
  { id: 'pronouns', icon: 'Noun', descKey: 'pronouns' },
  { id: 'interrogatives', icon: 'Check', descKey: 'interrogatives' },
];

export const COMMON_VERBS = [
  "sein", "haben", "werden", "können", "müssen", "sagen", "machen", "geben", "kommen", "sollen",
  "wollen", "gehen", "wissen", "sehen", "lassen", "stehen", "finden", "bleiben", "liegen", "heißen",
  "denken", "nehmen", "tun", "dürfen", "glauben", "halten", "nennen", "mögen", "zeigen", "führen",
  "sprechen", "bringen", "leben", "fahren", "meinen", "fragen", "kennen", "gelten", "stellen", "spielen",
  "arbeiten", "brauchen", "folgen", "lernen", "bestehen", "verstehen", "setzen", "bekommen", "beginnen", "erzählen",
  "versuchen", "schreiben", "laufen", "erklären", "entsprechen", "sitzen", "ziehen", "scheinen", "fallen", "gehören",
  "entstehen", "erhalten", "treffen", "suchen", "legen", "vorstellen", "handeln", "erreichen", "tragen", "schaffen",
  "lesen", "verlieren", "darstellen", "erkennen", "entwickeln", "reden", "aussehen", "erscheinen", "bilden", "anfangen",
  "erwarten", "wohnen", "betreffen", "warten", "vergehen", "helfen", "gewinnen", "schließen", "fühlen", "bieten"
];

export const GRAMMAR_LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];

const getLanguageName = (code: LanguageCode): string => {
  const map: Record<LanguageCode, string> = {
    ar: "Arabic",
    en: "English",
    de: "German",
    uk: "Ukrainian",
    es: "Spanish",
    tr: "Turkish",
    ru: "Russian",
    hu: "Hungarian",
    fa: "Persian",
    sr: "Serbian",
    fr: "French",
    it: "Italian",
    ja: "Japanese",
    "zh-CN": "Chinese (Simplified)",
    ur: "Urdu",
    ro: "Romanian",
    hi: "Hindi"
  };
  return map[code] || "English";
}

export const getNounPrompt = (lang: LanguageCode) => `
You are a German grammar expert for ${getLanguageName(lang)} speakers.
Task: Identify the definite article (der, die, or das) and the plural form for the given German noun.
Input Noun: "{noun}"
Output Format: JSON only.
Schema:
{
  "article": "der" | "die" | "das",
  "word": "The noun properly capitalized",
  "plural": "The plural form including article (e.g. die Tische)",
  "translation": "The translation of the noun in ${getLanguageName(lang)}"
}
`;

export const getVerbConjugationPrompt = (lang: LanguageCode) => `
You are a German grammar expert for ${getLanguageName(lang)} speakers.
Task: Conjugate the German verb "{verb}" in the specific form: "{category} - {subcategory}".
If the category is Passive, use "Vorgangspassiv".
Provide a simple, clear German example sentence for EACH pronoun using the conjugated form, along with its ${getLanguageName(lang)} translation.

Output Format: JSON only.
Schema:
{
  "conjugations": [
    {
      "pronoun": "ich" (or equivalent for the form),
      "conjugation": "verb form",
      "exampleDe": "German sentence",
      "exampleAr": "${getLanguageName(lang)} translation"
    }
    ... (for all pronouns: du, er/sie/es, wir, ihr, sie/Sie)
  ]
}
`;

export const getVerbMeaningsPrompt = (lang: LanguageCode) => `
You are a German grammar expert for ${getLanguageName(lang)} speakers.
Task: List the most common meanings and distinct usages of the German verb "{verb}".
For each usage, provide:
1. The meaning in ${getLanguageName(lang)}.
2. A simple German example sentence.
3. The ${getLanguageName(lang)} translation of the sentence.

Output Format: JSON only.
Schema:
{
  "meanings": [
    {
      "meaning": "Meaning in ${getLanguageName(lang)}",
      "exampleDe": "German Example",
      "exampleAr": "${getLanguageName(lang)} Translation"
    }
  ]
}
Provide between 3 to 5 distinct meanings/usages.
`;

export const getNounCasesPrompt = (lang: LanguageCode) => `
You are a German grammar expert for ${getLanguageName(lang)} speakers.
Task: Create simple German example sentences for the noun "{article} {noun}" in the four grammatical cases.
Provide the ${getLanguageName(lang)} translation for each.

Cases to cover:
1. Nominativ
2. Akkusativ
3. Dativ
4. Genitiv

Output Format: JSON only.
Schema:
{
  "cases": [
    {
      "caseName": "Nominativ",
      "sentenceDe": "German sentence",
      "sentenceAr": "${getLanguageName(lang)} translation"
    },
    ... (for Akkusativ, Dativ, Genitiv)
  ]
}
`;

export const getGrammarTopicsPrompt = (lang: LanguageCode) => `
You are a German curriculum expert for ${getLanguageName(lang)} students.
Task: List the 8 most important grammar topics specifically for level {level}.
Output Format: JSON only.
Schema:
{
  "topics": [
    {
      "id": "unique_id",
      "titleAr": "${getLanguageName(lang)} Title",
      "titleDe": "German Title (e.g., Bestimmter Artikel)",
      "description": "Short ${getLanguageName(lang)} description of what is covered"
    }
  ]
}
`;

export const getGrammarExplanationPrompt = (lang: LanguageCode) => `
You are a German teacher explaining to a ${getLanguageName(lang)} student.
Task: Explain the grammar topic "{titleDe} ({titleAr})" for level {level}.
1. Provide a clear, comprehensive explanation in ${getLanguageName(lang)} (Markdown supported).
2. Provide 3-5 clear German examples with ${getLanguageName(lang)} translations.

Output Format: JSON only.
Schema:
{
  "title": "Topic Title",
  "explanation": "Detailed explanation in ${getLanguageName(lang)} using Markdown",
  "examples": [
    {
      "de": "German sentence",
      "ar": "${getLanguageName(lang)} translation"
    }
  ]
}
`;

export const getToolsListPrompt = (lang: LanguageCode) => `
You are a German language expert for ${getLanguageName(lang)} speakers.
Task: List the 20 most important German {categoryName} ({categoryId}) for learners, sorted from easiest (A1) to hardest (C1).
For each item, provide:
1. The German word/phrase.
2. The CEFR Level (A1, A2, B1, B2, C1).
3. ${getLanguageName(lang)} translation.
4. A very short ${getLanguageName(lang)} description of its function (3-5 words).

Output Format: JSON only.
Schema:
{
  "tools": [
    {
      "word": "German word",
      "translation": "${getLanguageName(lang)} translation",
      "level": "A1" | "A2" | "B1" | "B2" | "C1",
      "description": "Short function description in ${getLanguageName(lang)}"
    }
  ]
}
`;

export const getToolDetailPrompt = (lang: LanguageCode) => `
You are a German teacher explaining the word "{word}" ({categoryName}) to a ${getLanguageName(lang)} student.
Level: {level}.
Task:
1. Explain the meaning and specific usage of this word in ${getLanguageName(lang)} (Markdown supported). Mention if it affects word order (e.g., nebensatz) or case (e.g., dativ).
2. Provide 3 distinct German example sentences with ${getLanguageName(lang)} translations.

Output Format: JSON only.
Schema:
{
  "word": "{word}",
  "level": "{level}",
  "meaningAr": "Meaning in ${getLanguageName(lang)}",
  "usageAr": "Explanation of usage in ${getLanguageName(lang)} (Markdown)",
  "examples": [
    {
      "de": "German example",
      "ar": "${getLanguageName(lang)} translation"
    }
  ]
}
`;

export const getChatSystemInstruction = (lang: LanguageCode) => `
You are a friendly German language tutor for ${getLanguageName(lang)} speakers.
The user is asking a question about a specific example sentence.
Context German: "{contextDe}"
Context Native: "{contextAr}"
Answer the user's question clearly and briefly in ${getLanguageName(lang)}. Explain the grammar rule or vocabulary if asked.
`;

export const getConversationPrompt = (lang: LanguageCode, length: string, isAustrian: boolean) => `
You are a German language teacher creating a dialogue for a ${getLanguageName(lang)} student.
Level: {level} (Strictly adhere to this level's vocabulary and grammar).
Topic: "{topic}"
Length: {length} (Short=4 turns, Medium=8 turns, Long=12 turns).

IMPORTANT ROLE DEFINITION:
- Speaker A: The STUDENT/USER (Learning German).
- Speaker B: The INTERLOCUTOR/TEACHER/OTHER (Native German Speaker, e.g. Waiter, Doctor, Clerk).

${isAustrian ? `IMPORTANT - AUSTRIAN DIALECT MODE ACTIVE:
The conversation MUST be in Viennese Dialect (Wienerisch). Use vocabulary like 'Servus', 'Grüss Gott', 'Leiwand', 'Oida'. Replace standard German words with Austrian equivalents (e.g., sentences ending with "g'schafft", use "Sackerl" instead of "Tüte", "Erdäpfel" instead of "Kartoffeln", "Paradeiser" instead of "Tomaten") while maintaining the selected CEFR level.

CRITICAL INSTRUCTION FOR AUDIO:
In the "ttsText" field, you MUST provide a Standard German approximation or phonetic spelling of the dialect phrase so that a text-to-speech engine can pronounce it correctly without failing. For example, if "textDe" is "G'schamster Diener", "ttsText" should be "Geschamster Diener" or similar.
` : ''}

Task: Generate a realistic dialogue between Person A (User) and Person B (Other) about this topic.
Start with Speaker B (Other) asking a question or greeting, OR Speaker A (User) initiating.
STRICTLY maintain the context of the topic "{topic}". Do NOT change the subject.

Format: JSON only.
Schema:
{
  "conversation": [
    {
      "speaker": "A" | "B",
      "textDe": "German sentence (Dialect if mode active)",
      "ttsText": "Pronounceable text (Optional, required if Dialect)",
      "textAr": "${getLanguageName(lang)} translation"
    }
  ]
}
`;

export const getConversationExtensionPrompt = (lang: LanguageCode, isAustrian: boolean) => `
You are a German language teacher extending a dialogue.
Level: {level}.
Topic Context: The conversation is strictly about "{topic}". DO NOT deviate from this topic.

IMPORTANT ROLE DEFINITION:
- Speaker A: The STUDENT/USER (You are NOT generating this, the user provided it).
- Speaker B: The INTERLOCUTOR/TEACHER/OTHER (Native German Speaker).

${isAustrian ? `IMPORTANT - AUSTRIAN DIALECT MODE ACTIVE:
Speaker B MUST reply in Viennese Dialect (Wienerisch). Use words like 'Servus', 'Oida', 'Leiwand', 'Sackerl'. Use Austrian grammar nuances where appropriate for the level.

CRITICAL INSTRUCTION FOR AUDIO:
In the "ttsText" field, you MUST provide a Standard German approximation or phonetic spelling of the dialect phrase so that a text-to-speech engine can pronounce it correctly without failing.` : ''}

User Input (Person A) says: "{userInput}"

Task:
1. Output the User's input as the first turn for **Speaker A**.
2. Generate a response from **Speaker B** relevant to the topic "{topic}".
3. Continue the conversation naturally (Total 2-4 turns).

Format: JSON only.
Schema:
{
  "conversation": [
    {
      "speaker": "A",
      "textDe": "User input",
      "ttsText": "Pronounceable text",
      "textAr": "${getLanguageName(lang)} translation"
    },
    {
      "speaker": "B",
      "textDe": "Response from B",
      "ttsText": "Pronounceable text",
      "textAr": "Translation"
    }
  ]
}
`;

export const getKeywordsPrompt = (lang: LanguageCode) => `
Task: Extract the 5 most important/difficult German keywords from the text provided.
Target Audience: ${getLanguageName(lang)} speaker learning German.
Format: JSON only.
Schema:
{
  "keywords": [
    {
      "word": "German Word",
      "meaning": "${getLanguageName(lang)} Meaning"
    }
  ]
}
`;
